version: '3.8'

services:
  # Redis database
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shop-network

  # User service
  user-service:
    build: ./services/user-service
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=dev-secret-key-change-in-production
      - NODE_ENV=development
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - shop-network

  # Product service
  product-service:
    build: ./services/product-service
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - REDIS_URL=redis://redis:6379
      - USER_SERVICE_URL=http://user-service:8081
      - NODE_ENV=development
    depends_on:
      redis:
        condition: service_healthy
      user-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - shop-network

  # Order service
  order-service:
    build: ./services/order-service
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
      - REDIS_URL=redis://redis:6379
      - USER_SERVICE_URL=http://user-service:8081
      - PRODUCT_SERVICE_URL=http://product-service:8082
      - NODE_ENV=development
    depends_on:
      redis:
        condition: service_healthy
      user-service:
        condition: service_healthy
      product-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8083/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - shop-network

volumes:
  redis-data:

networks:
  shop-network:
    driver: bridge